# https://github.com/ferjgar/youtube-backup
---
- name: Install yarn repository
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    force: yes

- name: Install yarn
  yum:
    name: yarn
    state: latest

- name: Install youtube-dl
  get_url:
    url: https://yt-dl.org/downloads/latest/youtube-dl
    dest: /usr/local/bin/youtube-dl
    mode: a+rx
    force: yes
